/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.major_pro.airlinemanagementsystem;

/**
 *
 * @author pappu
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Add_Customer_Menu = new javax.swing.JMenu();
        Add_Menu_Customer = new javax.swing.JMenuItem();
        Search_Menu = new javax.swing.JMenuItem();
        TicketFlight_Menu = new javax.swing.JMenu();
        BookTicket_Menu = new javax.swing.JMenuItem();
        Add_Flight_Menu = new javax.swing.JMenuItem();
        Generate_Report_Menu = new javax.swing.JMenuItem();
        Create_Admin_Menu = new javax.swing.JMenu();
        Add_User_Menu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(740, 600));

        jDesktopPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(50, 50));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(730, 650));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        Add_Customer_Menu.setText("Add Customer");
        Add_Customer_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_Customer_MenuActionPerformed(evt);
            }
        });

        Add_Menu_Customer.setText("Add");
        Add_Menu_Customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_Menu_CustomerActionPerformed(evt);
            }
        });
        Add_Customer_Menu.add(Add_Menu_Customer);

        Search_Menu.setText("Search");
        Search_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_MenuActionPerformed(evt);
            }
        });
        Add_Customer_Menu.add(Search_Menu);

        jMenuBar1.add(Add_Customer_Menu);

        TicketFlight_Menu.setText("Tickets & Flights");
        TicketFlight_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicketFlight_MenuActionPerformed(evt);
            }
        });

        BookTicket_Menu.setText("Book Tickets");
        BookTicket_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookTicket_MenuActionPerformed(evt);
            }
        });
        TicketFlight_Menu.add(BookTicket_Menu);

        Add_Flight_Menu.setText("Add Flight");
        Add_Flight_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_Flight_MenuActionPerformed(evt);
            }
        });
        TicketFlight_Menu.add(Add_Flight_Menu);

        Generate_Report_Menu.setText("Generate Report");
        Generate_Report_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Generate_Report_MenuActionPerformed(evt);
            }
        });
        TicketFlight_Menu.add(Generate_Report_Menu);

        jMenuBar1.add(TicketFlight_Menu);

        Create_Admin_Menu.setText("Create Admin");

        Add_User_Menu.setText("Add User");
        Add_User_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_User_MenuActionPerformed(evt);
            }
        });
        Create_Admin_Menu.add(Add_User_Menu);

        jMenuBar1.add(Create_Admin_Menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Add_Menu_CustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_Menu_CustomerActionPerformed
        // TODO add your handling code here:
        AddCustomer newcustomer = new AddCustomer();
        newcustomer.setVisible(true);
        jDesktopPane1.add(newcustomer);
    }//GEN-LAST:event_Add_Menu_CustomerActionPerformed

    private void Add_Customer_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_Customer_MenuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Add_Customer_MenuActionPerformed

    private void Search_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_MenuActionPerformed
        // TODO add your handling code here:
        SearchCustomer search = new SearchCustomer();
        search.setVisible(true);
        jDesktopPane1.add(search);
    }//GEN-LAST:event_Search_MenuActionPerformed

    private void BookTicket_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookTicket_MenuActionPerformed
        // TODO add your handling code here:
        BookTicket newTicket = new BookTicket();
        newTicket.setVisible(true);
        jDesktopPane1.add(newTicket);
    }//GEN-LAST:event_BookTicket_MenuActionPerformed

    private void Add_Flight_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_Flight_MenuActionPerformed
        // TODO add your handling code here:
        AddFlight flight = new AddFlight();
        flight.setVisible(true);
        jDesktopPane1.add(flight);
    }//GEN-LAST:event_Add_Flight_MenuActionPerformed

    private void TicketFlight_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicketFlight_MenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TicketFlight_MenuActionPerformed

    private void Add_User_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_User_MenuActionPerformed
        // TODO add your handling code here:
        AdminWindow user = new AdminWindow();
        user.setVisible(true);
        jDesktopPane1.add(user);
    }//GEN-LAST:event_Add_User_MenuActionPerformed

    private void Generate_Report_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Generate_Report_MenuActionPerformed
        // TODO add your handling code here:
        Report r = new Report();
        r.setVisible(true);
        jDesktopPane1.add(r);
    }//GEN-LAST:event_Generate_Report_MenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Add_Customer_Menu;
    private javax.swing.JMenuItem Add_Flight_Menu;
    private javax.swing.JMenuItem Add_Menu_Customer;
    private javax.swing.JMenuItem Add_User_Menu;
    private javax.swing.JMenuItem BookTicket_Menu;
    private javax.swing.JMenu Create_Admin_Menu;
    private javax.swing.JMenuItem Generate_Report_Menu;
    private javax.swing.JMenuItem Search_Menu;
    private javax.swing.JMenu TicketFlight_Menu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
